### ISSUE TITLE
Auto login

### ISSUE THREAD

**Issue by grdaneault** [RITHonorsTechCommittee/gimme-your-files-please#31]
Sometimes the login/logout functionality is funky and doesn't persist correctly.  If possible, you should really only have to log in once, and then the correct page would still be present

**Comment by grdaneault** [comment]
This might need to be done with a cookie to store the logged in user

**Comment by regdoug** [comment]
I'm going to mark this as wontfix.  There are too many quirks with multiple signin to even bother.
