### ISSUE TITLE
"Give To" Button

### ISSUE THREAD

**Issue by grdaneault** [RITHonorsTechCommittee/gimme-your-files-please#59]
We need to be able to assign new users permissions on existing files.  The should be able to specify reader, writer, or owner as the new role of all the files in the folder.

**Comment by regdoug** [comment]
I'm not sure if we really need this. Adding someone as reader or writer is as simple as sharing the parent folder with them. And do we really need a give ownership or is it sufficient to have the user simply ask for the files? 



—
Reginald Pierce 
pierce.reginald@gmail.com

**Comment by grdaneault** [comment]
I'm pretty sure we do, at least for the ownership.  If the new owner has no
access to the files in the folder they won't be able to list them for the
transfer

**Comment by regdoug** [comment]
But wouldn't they normallly already be an editor?

**Comment by grdaneault** [comment]
In general, yeah I guess they would.  We'll probably need to specify in
some directions that they need to be added to the folder before using the
tool
