### ISSUE TITLE
Logo Ideas?

### ISSUE THREAD

**Issue by regdoug** [RITHonorsTechCommittee/gimme-your-files-please#6]
I was thinking about this and I thought a neat logo might be a "bathroom-icon" style figure with an outstretched arm and the four google colors around his "hand"...

We could also try to make this a competition for Honors Students.  Something Erin mentioned to me today is that it would be neat to have tech committee organize "techie" activities with Activities committee.

Thoughts?

**Comment by grdaneault** [comment]
we've got the folder thing, which is good enough for now.
