### ISSUE TITLE
Only one transfer request can be in system per recipient

### ISSUE THREAD

**Issue by regdoug** [RITHonorsTechCommittee/gimme-your-files-please#66]
Steps to reproduce bug:

1. Bob sends a transfer request (TR) for files in folder A to user Alice
2. Alice responds to the TR, but does not delete it (this might not be required, but that is how I encountered it)
3. Bob sends another TR to Alice for files in folder B

We expect that Alice will get another email with a link to the new TR for folder B.
What actually happens is that Alice gets another email with a link to the old TR, which is now empty of files.

If Alice deletes the original TR, then Bob can create a new TR and the correct link will be sent, but no more than one TR can be in the system per recipient.

**Comment by grdaneault** [comment]
This is partially be design, so if a transfer request already exists for a given requester/requestee pair, it is supposed to just add the files from the new transfer.  I think in my new branch fix-multi-requests this has been changed slightly so it will only do this if the folder id is the same as well.

It also fixes the deletion (or lack thereof) of requests after all files have been transferred.  Once I get it merged I'll put it up on appengine and you can retest.
