### ISSUE TITLE
Refresh required before files show up

### ISSUE THREAD

**Issue by regdoug** [RITHonorsTechCommittee/gimme-your-files-please#67]
After logging in, the manage page doesn't show any files.  If you click the refresh button, they all show up.

**Comment by regdoug** [comment]
This did not used to happen, and it doesn't happen on the feature branch I am currently working on, so the problem was introduced sometime since commit faa1134

**Comment by grdaneault** [comment]
I can't reproduce this.  What folder are you loading?

**Comment by regdoug** [comment]
I was loading https://gimmeyourfilesplease.appspot.com/#/manage/0B4UTey76Pp14U0sxOGtSNGxGSTA

It does seem to be working now, so maybe it was just a two-time glitch.
