### ISSUE TITLE
Add requests to push queue

### ISSUE THREAD

**Issue by grdaneault** [RITHonorsTechCommittee/gimme-your-files-please#9]
Google App Engine has a feature for Push queues and Pull queues.  A push queue allows tasks to be enqueued by any user and then the system will automatically execute them when it is able.  This is a perfect mechanism for sending the transfer request notification emails.

We need a push queue that can periodically send out the emails, as generated in #8

**Comment by regdoug** [comment]
Is this implemented? If not, is is needed?

**Comment by grdaneault** [comment]
Nope, this is no longer needed.  We're just sending the request in the api call, the overhead doesn't appear to be that bad and we don't need the added complexity.
